[package]
name = "chatui_server"
version = "0.1.0"
edition = "2018"
authors = ["grvxs gauravsinghsisodia5@gmail.com"]
repository = "https://github.com/grvxs/chatui"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0.64"
